apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-keqj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhvr-tenant/rhtap-demo-app/hacbs-test-project-keqj@sha256:e2b8c687147f9f6a141df36c53cb3b67e80a55383a2a8070ff0b370bef811c76
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
