apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-keqj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhvr-tenant/rhtap-demo-app/hacbs-test-project-keqj@sha256:10cbaa095a8e94e9afff2fa4a51d8a1a7dceec8e84f1459ab869ab210428970b
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
