apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-keqj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-keqj
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-keqj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-keqj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-keqj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhvr-tenant/rhtap-demo-app/hacbs-test-project-keqj@sha256:10cbaa095a8e94e9afff2fa4a51d8a1a7dceec8e84f1459ab869ab210428970b
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
